### ISSUE TITLE
Some small design things

### ISSUE THREAD

**Issue by SillyGoose123** [vKxni/discordindex#2]
- In the dark mode there are missing the server infos.
![image](https://user-images.githubusercontent.com/118613840/231306005-eb482199-7b19-4ff2-b55a-72f36aa9d252.png)
![image](https://user-images.githubusercontent.com/118613840/231306044-92973b4e-5641-4f0f-b1b2-ad3c3ed10978.png)

- In the dark mode you can't see the search.
![image](https://user-images.githubusercontent.com/118613840/231305892-b9e8b75f-af80-4f8d-b4cd-ee7399d619eb.png)
![image](https://user-images.githubusercontent.com/118613840/231305665-697e8f15-e674-439b-911d-abebab467a5e.png)

(Please make the blue mode as standard)

@SillyCodeDev

**Comment by vKxni** [comment]
Thanks! I must say that this depends on your preference settings of your device. On my Desktop it’s different as on my iPhone actually but I will see what I can do. It’s a good idea to keep the -dark- version as the main design.

**Comment by vKxni** [comment]
> * In the dark mode there are missing the server infos.
>   ![image](https://user-images.githubusercontent.com/118613840/231306005-eb482199-7b19-4ff2-b55a-72f36aa9d252.png)
>   ![image](https://user-images.githubusercontent.com/118613840/231306044-92973b4e-5641-4f0f-b1b2-ad3c3ed10978.png)
> * In the dark mode you can't see the search.
>   ![image](https://user-images.githubusercontent.com/118613840/231305892-b9e8b75f-af80-4f8d-b4cd-ee7399d619eb.png)
>   ![image](https://user-images.githubusercontent.com/118613840/231305665-697e8f15-e674-439b-911d-abebab467a5e.png)
> 
> (Please make the blue mode as standard)
> 
> @SillyCodeDev

![Uploading BAEAFFEB-0BD9-4CDF-A30C-2746DCFB7F30.png…]()

**Comment by vKxni** [comment]
![CED6601F-3E3E-46FA-9D44-A5F5EE4A7E37](https://user-images.githubusercontent.com/74613145/231347878-c09767ea-3ee3-43f2-87da-b5a7aed85682.png)

**Comment by vKxni** [comment]
![Uploading F66F6FC2-8598-4128-B998-670201EE8D9D.png…]()

**Comment by vKxni** [comment]
2:
![68DB3E7D-A059-42D9-A106-2BE26BF316FB](https://user-images.githubusercontent.com/74613145/231348389-0f58470c-39fd-4a8f-adce-97104cdb32ad.png)
